# Generated by Django 6.0.3 on 2026-04-07 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_add_slug_to_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="zip",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
