# Generated by Django 6.0.3 on 2026-04-11 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_auto_20260407_1502"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="updated_at",
            field=models.DateField(auto_now=True),
        ),
    ]
