# Generated by Django 6.0.3 on 2026-04-11 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_product_updated_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="updated_at",
        ),
    ]
